# Generated by Django 3.1.5 on 2021-01-24 15:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=150)),
                ('Location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.IntegerField(default=datetime.date(2021, 1, 24))),
                ('lastEditDateTime', models.IntegerField(default=datetime.time(15, 50, 56, 502750))),
                ('noteTitle', models.CharField(max_length=150)),
                ('noteDescription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('owner_username', models.CharField(blank=True, max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='serviceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('wiring', 'Car wiring'), ('tyres', 'Wheel Alignment'), ('electric', 'Electric Cars'), ('engine', 'Engine Checking')], max_length=32)),
                ('owner_username', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, choices=[('kampala', 'Kampala'), ('kayinga', 'Kayinga'), ('katwe', 'Katwe'), ('kakiri', 'Kakiri')], max_length=32)),
                ('name', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('other', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
