# Generated by Django 3.1.5 on 2021-01-24 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.FileField(blank=True, upload_to='media/photos/service_provider_avatars/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='lastEditDateTime',
            field=models.IntegerField(default=datetime.time(18, 31, 11, 717128)),
        ),
    ]
