# Generated by Django 3.1.5 on 2021-02-15 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210208_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createDateTime',
            field=models.IntegerField(default=datetime.date(2021, 2, 15)),
        ),
        migrations.AlterField(
            model_name='note',
            name='lastEditDateTime',
            field=models.IntegerField(default=datetime.time(7, 22, 35, 63679)),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(blank=True, choices=[('kampala', 'Kampala'), ('kayinga', 'Kayinga'), ('kakiri', 'Kakiri'), ('Nsambya', 'Nsambya'), ('Entebbe', 'Entebbe'), ('Munyonyo', 'Munyonyo'), ('Kiboga', 'Kiboga'), ('Mityana', 'Mityana'), ('Lugazi', 'Lugazi'), ('Kamuli', 'Kamuli'), ('Iganga', 'Iganga'), ('Kitgum', 'Kitgum'), ('Mbarara', 'Mbarara'), ('Gulu', 'Gulu')], max_length=32),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(blank=True, choices=[('Car wiring', 'Car wiring'), ('Wheel Alignment', 'Wheel Alignment'), ('Electric Cars', 'Electric Cars'), ('Engine Checking', 'Engine Checking'), ('Wheel Balancing', 'Wheel Balancing'), ('Flat Tyres', 'Flat Tyres'), ('Computer Aided Mechanics', 'Computer Aided Mechanics')], max_length=32),
        ),
    ]
