# Generated by Django 3.1.5 on 2021-02-15 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210215_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastEditDateTime',
            field=models.IntegerField(default=datetime.time(7, 29, 3, 558832)),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(blank=True, choices=[('wiring', 'Car wiring'), ('Alignment', 'Wheel Alignment'), ('Electrics', 'Electric Cars'), ('Engines', 'Engine Checking'), ('Wheel_Balancing', 'Wheel Balancing'), ('Flat_Tyres', 'Flat Tyres'), ('Computer_Aided_Mechanics', 'Computer Aided Mechanics')], max_length=32),
        ),
    ]
