# Generated by Django 3.1.5 on 2021-10-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211004_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
