# Generated by Django 3.1.5 on 2021-10-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211019_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='on_leave',
            field=models.CharField(blank=True, choices=[('pass_leave', 'Pass leave'), ('annual_leave', 'Annual leave'), ('maternity_leave', 'Marternity leave'), ('not_on_leave', 'Not on leave')], max_length=100, null=True),
        ),
    ]
