# Generated by Django 3.1.5 on 2021-10-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211019_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('un_agencies', 'UN AGENCIES'), ('embassy_high', 'EMBASSY HIGH'), ('jlot', 'JLOT'), ('body_gaurd', 'BODY GUARD'), ('authorities', 'AUTHORITIES'), ('ministries', 'MINISTRIES')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('commander', 'Commander'), ('deputy_commander', 'Deputy Commander'), ('staff_officer', 'Staff Officer'), ('armoury', 'Armoury'), ('head_operations', 'Head Operations')], max_length=100, null=True),
        ),
    ]
